### PR TITLE
Create list of curated blog posts

### PR DESCRIPTION
**Pull request by AndreiVidrasco**
Copied list of curated blog posts from https://codeshare.io/sysdesign to avoid loss of information

### CODE REVIEW

**Comment by weeeBox** [comment]
Can you sign the [Individual Contributor License Agreement (CLA)](https://forms.gle/oqgHfGiJZ28KJy7w9)?

**Comment by AndreiVidrasco** [comment]
I already filled, 4 hours ago, when I opened PR
CleanShot 2022-04-12 at 23 11 54@2x

**Review by weeeBox — APPROVED** [review]
~~~~~~~~~~~
~~~🛳⛴🚢~~~
~~~~~~~~~~~

**Comment by AndreiVidrasco** [comment]
I don't have merge button enabled, @weeeBox can you press it?
CleanShot 2022-04-13 at 10 05 23@2x

**Comment by AndreiVidrasco** [comment]
@weeeBox  reminder? 
or should I fix anything else before merging?

**Pull request merged**
